const C=window.CORA_CONFIG,D=window.CORA_DATA;
const brl=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0);
const $=id=>document.getElementById(id);
const pages=[...document.querySelectorAll('.page')],tabs=[...document.querySelectorAll('#nav button')];
function go(id){pages.forEach(p=>p.classList.toggle('active',p.id===id));tabs.forEach(b=>b.classList.toggle('active',b.dataset.tab===id));window.scrollTo(0,0)}
tabs.forEach(b=>b.onclick=()=>go(b.dataset.tab));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));

const serieSel=$('serieSel'),planoSel=$('planoSel'),condSel=$('condSel'),anuidadeCheck=$('anuidadeCheck'),primeiraCheck=$('primeiraCheck'),materialCheck=$('materialCheck'),uniformList=$('uniformList');
D.series.forEach(s=>serieSel.add(new Option(s.nome,s.id)));
let qties={};
function serie(){return D.series.find(s=>s.id===serieSel.value)}
function mensalidadeData(){const s=serie(),m=D.mensalidades[s.segmento],pl=planoSel.value,co=condSel.value,p=m['plano'+pl];return{s,m,p,co,monthly:p[co],annual:co==='ate'?m.anuidadeAte:m.anuidadeApos}}
function uniforms(){const s=serie();return D.fardamento[s.segmento].filter(x=>!x.restrito||x.restrito.includes(s.id))}
function selectedUniforms(){return uniforms().filter(u=>(qties[u.nome]||0)>0)}
function renderUniforms(){const rows=uniforms();uniformList.innerHTML=rows.map((u,i)=>`<div class='uniform'><div><b>${u.nome}</b><br><small>${brl(u.valor)}</small></div><div class='qty'><button data-i='${i}' data-d='-1'>−</button><span>${qties[u.nome]||0}</span><button data-i='${i}' data-d='1'>+</button></div></div>`).join('');uniformList.querySelectorAll('button').forEach(b=>b.onclick=()=>{const u=rows[+b.dataset.i],d=+b.dataset.d;qties[u.nome]=Math.max(0,(qties[u.nome]||0)+d);renderUniforms();calc()})}
function cartCount(){let n=0;if(anuidadeCheck.checked)n++;if(primeiraCheck.checked)n++;if(materialCheck.checked)n++;Object.values(qties).forEach(q=>n+=q||0);return n}
function updateCart(){const n=cartCount();$('cartBadge').textContent=n;$('cartNavCount').textContent=n;$('cartCountText').textContent=`${n} ${n===1?'item selecionado':'itens selecionados'}`}
function quoteValues(){const {s,m,p,co,monthly,annual}=mensalidadeData();const primeira=m.primeira;const mat=materialCheck.checked?s.material:0;let mens=0;if(anuidadeCheck.checked)mens=annual;else if(primeiraCheck.checked)mens=primeira;const f=uniforms().reduce((sum,u)=>sum+u.valor*(qties[u.nome]||0),0);return{s,m,p,co,monthly,annual,primeira,mat,f,mens,total:mens+mat+f}}
function renderSelectedItems(v){const items=[];if(anuidadeCheck.checked)items.push(`Anuidade 2026 — ${brl(v.annual)}`);if(primeiraCheck.checked)items.push(anuidadeCheck.checked?`1ª parcela — ${brl(v.primeira)} (já incluída na anuidade)`:`1ª parcela — ${brl(v.primeira)}`);if(materialCheck.checked)items.push(`Livros / material didático — ${brl(v.mat)}`);selectedUniforms().forEach(u=>items.push(`${u.nome} × ${qties[u.nome]} — ${brl(u.valor*(qties[u.nome]||0))}`));$('selectedItemsList').innerHTML=items.length?items.map(x=>`<div class='selected-row'>✓ ${x}</div>`).join(''):`<div class='empty-cart'>Nenhum item selecionado.</div>`}
function calc(){const v=quoteValues();$('primeiraVal').textContent=brl(v.primeira);$('mensalVal').textContent=brl(v.monthly);$('mensalDesc').textContent=`${v.p.parcelas} parcelas`;$('anuidadeVal').textContent=brl(v.annual);$('anuidadeChoiceVal').textContent=brl(v.annual);$('primeiraChoiceVal').textContent=brl(v.primeira);$('materialChoiceVal').textContent=brl(v.s.material);$('sumMens').textContent=brl(v.mens);$('sumMat').textContent=brl(v.mat);$('sumFarda').textContent=brl(v.f);$('sumTotal').textContent=brl(v.total);renderSelectedItems(v);updateCart()}
[serieSel,planoSel,condSel,anuidadeCheck,primeiraCheck,materialCheck].forEach(e=>e.onchange=()=>{if(e===serieSel)qties={};renderUniforms();calc()});renderUniforms();calc();

function quoteText(){const v=quoteValues();const lines=[`Cora Família — estimativa 2026`,v.s.nome,`Plano ${planoSel.value} — ${condSel.options[condSel.selectedIndex].text}`,''];if(anuidadeCheck.checked)lines.push(`Anuidade: ${brl(v.annual)}`);if(primeiraCheck.checked)lines.push(anuidadeCheck.checked?`1ª parcela: ${brl(v.primeira)} (incluída na anuidade)`:`1ª parcela: ${brl(v.primeira)}`);if(materialCheck.checked)lines.push(`Livros / material didático: ${brl(v.mat)}`);selectedUniforms().forEach(u=>lines.push(`${u.nome} x ${qties[u.nome]}: ${brl(u.valor*(qties[u.nome]||0))}`));lines.push('',`Total estimado: ${brl(v.total)}`,'','*Simulação informativa. Confirme condições com a escola.');return lines.join('\n')}
$('shareQuote').onclick=async()=>{const txt=quoteText();if(navigator.share){try{await navigator.share({title:'Cora Família - Orçamento',text:txt})}catch(e){}}else{navigator.clipboard.writeText(txt);alert('Orçamento copiado.')}};

function pdfHtml(){const v=quoteValues(),logo=new URL('logo-escola.png',location.href).href;const rows=[];if(anuidadeCheck.checked)rows.push(['Anuidade 2026',brl(v.annual)]);if(primeiraCheck.checked)rows.push(['1ª parcela',anuidadeCheck.checked?`${brl(v.primeira)} — incluída na anuidade`:brl(v.primeira)]);if(materialCheck.checked)rows.push(['Livros / material didático',brl(v.mat)]);selectedUniforms().forEach(u=>rows.push([`${u.nome} × ${qties[u.nome]}`,brl(u.valor*(qties[u.nome]||0))]));return `<!doctype html><html><head><meta charset='utf-8'><title>Orçamento Cora Família - ${v.s.nome}</title><style>@page{size:A4;margin:16mm}body{font-family:Arial;color:#102841;margin:0}.head{display:flex;align-items:center;gap:14px;border-bottom:4px solid #0f5ea8;padding-bottom:14px}.head img{width:78px;height:78px;object-fit:contain}h1{margin:0;color:#082e59}h2{color:#0f5ea8;margin-top:28px}.meta{background:#eef6fc;padding:14px;border-radius:10px;margin:18px 0;line-height:1.7}table{width:100%;border-collapse:collapse;margin-top:12px}th{background:#082e59;color:#fff;text-align:left;padding:10px}td{padding:10px;border-bottom:1px solid #dbe6ef}td:last-child{text-align:right;font-weight:700}.total{margin-top:18px;background:#e9f8f0;border-left:5px solid #1d9b69;padding:16px;font-size:22px;font-weight:900}.note{font-size:11px;color:#65788b;margin-top:24px}.footer{margin-top:34px;border-top:1px solid #dbe6ef;padding-top:10px;text-align:center;font-size:11px;color:#65788b}@media print{button{display:none}}</style></head><body><div class='head'><img src='${logo}'><div><small>COLÉGIO CORA CORALINA</small><h1>Cora Família</h1><div>Orçamento informativo 2026</div></div></div><div class='meta'><b>Série/segmento:</b> ${v.s.nome}<br><b>Plano:</b> Plano ${planoSel.value}<br><b>Condição:</b> ${condSel.options[condSel.selectedIndex].text}</div><h2>Itens selecionados</h2><table><thead><tr><th>Item</th><th>Valor</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td></tr>`).join(''):`<tr><td colspan='2'>Nenhum item selecionado.</td></tr>`}</tbody></table><div class='total'>Total estimado: ${brl(v.total)}</div><div class='note'>Simulação informativa baseada nos valores de referência de 2026. Valores, disponibilidade e condições devem ser confirmados com o Colégio Cora Coralina.</div><div class='footer'>Cora Família • Colégio Cora Coralina</div><script>window.onload=()=>setTimeout(()=>window.print(),350)<\/script></body></html>`}
$('downloadQuotePdf').onclick=()=>{const w=window.open('','_blank');if(!w){alert('Permita pop-ups para gerar o PDF.');return}w.document.open();w.document.write(pdfHtml());w.document.close()};

$('valueCards').innerHTML=D.series.map(s=>{const m=D.mensalidades[s.segmento];return `<div class='card' style='margin:10px 0'><h3>${s.nome}</h3><div class='grid'><div><small>Material didático</small><div class='big'>${brl(s.material)}</div></div><div><small>Plano A — até vencimento</small><div class='big'>${brl(m.planoA.ate)}</div><p>1ª ${brl(m.primeira)} + 12 parcelas</p></div><div><small>Plano B — até vencimento</small><div class='big'>${brl(m.planoB.ate)}</div><p>1ª ${brl(m.primeira)} + 11 parcelas</p></div></div></div>`}).join('');
$('phoneLink').href='tel:+55'+C.escola.telefone;$('phoneText').textContent=C.escola.telefoneExibicao;$('instaLink').href='https://instagram.com/'+C.escola.instagram;$('instaText').textContent='@'+C.escola.instagram;$('addressText').textContent=C.escola.endereco;if(C.escola.whatsapp){$('waLink').href='https://wa.me/'+C.escola.whatsapp;$('waLink').target='_blank';$('waText').textContent=C.escola.whatsappExibicao}else{$('waText').textContent='Número a confirmar';$('waLink').onclick=()=>alert('Cadastre o número oficial do WhatsApp em config.js.')}
let rating=0;document.querySelectorAll('.star').forEach(s=>s.onclick=()=>{rating=+s.dataset.v;document.querySelectorAll('.star').forEach(x=>x.classList.toggle('on',+x.dataset.v<=rating))});function localSave(record){const a=JSON.parse(localStorage.getItem('coraFeedbacks')||'[]');a.push(record);localStorage.setItem('coraFeedbacks',JSON.stringify(a))}$('sendFeedback').onclick=async()=>{if(!rating){$('feedbackStatus').style.color='#c64343';$('feedbackStatus').textContent='Escolha de 1 a 5 estrelas.';return}if(!$('fbFuncionario').value.trim()){$('feedbackStatus').style.color='#c64343';$('feedbackStatus').textContent='Informe o nome do funcionário.';return}const record={data:new Date().toISOString(),responsavel:$('fbNome').value.trim(),funcionario:$('fbFuncionario').value.trim(),canal:$('fbCanal').value,estrelas:rating,mensagem:$('fbMsg').value.trim()};let ok=false;if(C.feedbackEndpoint){try{const r=await fetch(C.feedbackEndpoint,{method:'POST',headers:{'Content-Type':'text/plain'},body:JSON.stringify(record)});ok=r.ok}catch(e){}}localSave(record);$('feedbackStatus').style.color='#1d9b69';$('feedbackStatus').textContent=ok?'Avaliação enviada. Obrigado!':'Avaliação registrada neste aparelho. A integração central será ativada na próxima etapa.';$('fbMsg').value='';rating=0;document.querySelectorAll('.star').forEach(x=>x.classList.remove('on'))};
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').hidden=false});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$('installBtn').hidden=true}else if(/iPhone|iPad|iPod/.test(navigator.userAgent)){alert('No Safari: Compartilhar → Adicionar à Tela de Início.')}};if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js');